/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog.retoequipo2;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM126
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private UsuarioDAO usuarios = new UsuarioDAO();
    private RutasDAO rutas = new RutasDAO();
    private MetodosDAO metodos = new MetodosDAO();
    private Usuario user = null;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        PantallaPrinci.setVisible(true);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(false);
        PantallaVerRutas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaPrinci = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnVerRutas = new javax.swing.JButton();
        PantallaVerRutas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRutas = new javax.swing.JTable();
        btnResena = new javax.swing.JButton();
        btnValoracion = new javax.swing.JButton();
        btnVolverVerRutas = new javax.swing.JButton();
        PantallaRegistro = new javax.swing.JPanel();
        textUsuario = new javax.swing.JTextField();
        btnEnviarInicioSesion = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PantallaMenu = new javax.swing.JPanel();
        btnVerRuta2 = new javax.swing.JButton();
        btnCrearRuta = new javax.swing.JButton();
        btnDescargarFicha = new javax.swing.JButton();
        btnCrearCalendar = new javax.swing.JButton();
        btnModificarRuta = new javax.swing.JButton();
        btnBorrarRuta = new javax.swing.JButton();
        btnValidarRuta = new javax.swing.JButton();
        btnValidarUsuario = new javax.swing.JButton();
        PantallaValidarRutas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaRutasNoValidadas = new javax.swing.JTable();
        btnValidaRUTA = new javax.swing.JButton();
        btnVolverValidaRutas = new javax.swing.JButton();
        PantallaValidarUsuarios = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        btnValidarUsuarios = new javax.swing.JButton();
        btnVolverValidaUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VPrincipal");
        getContentPane().setLayout(new java.awt.CardLayout());

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setToolTipText("btnIniciarSesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnVerRutas.setText("Ver Rutas");
        btnVerRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaPrinciLayout = new javax.swing.GroupLayout(PantallaPrinci);
        PantallaPrinci.setLayout(PantallaPrinciLayout);
        PantallaPrinciLayout.setHorizontalGroup(
            PantallaPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaPrinciLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addGap(75, 75, 75))
            .addGroup(PantallaPrinciLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnVerRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        PantallaPrinciLayout.setVerticalGroup(
            PantallaPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPrinciLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(btnVerRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );

        btnVerRutas.getAccessibleContext().setAccessibleName("BtnVerRutas");

        getContentPane().add(PantallaPrinci, "card2");

        PantallaVerRutas.setBorder(javax.swing.BorderFactory.createTitledBorder("Rutas"));

        jScrollPane1.setViewportView(TablaRutas);

        btnResena.setText("Reseñar Ruta");

        btnValoracion.setText("Dejar Valoracion");

        btnVolverVerRutas.setText("Volver");
        btnVolverVerRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverVerRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaVerRutasLayout = new javax.swing.GroupLayout(PantallaVerRutas);
        PantallaVerRutas.setLayout(PantallaVerRutasLayout);
        PantallaVerRutasLayout.setHorizontalGroup(
            PantallaVerRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaVerRutasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PantallaVerRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(PantallaVerRutasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVolverVerRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValoracion)
                        .addGap(241, 241, 241)
                        .addComponent(btnResena)))
                .addContainerGap())
        );
        PantallaVerRutasLayout.setVerticalGroup(
            PantallaVerRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaVerRutasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PantallaVerRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResena)
                    .addComponent(btnValoracion)
                    .addComponent(btnVolverVerRutas))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(PantallaVerRutas, "card3");

        PantallaRegistro.setToolTipText("PantallaRegistro");

        btnEnviarInicioSesion.setText("Enviar");
        btnEnviarInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarInicioSesionActionPerformed(evt);
            }
        });

        textPassword.setText("jPasswordField1");

        jLabel1.setText("Usuario");

        jLabel2.setText("Password");

        javax.swing.GroupLayout PantallaRegistroLayout = new javax.swing.GroupLayout(PantallaRegistro);
        PantallaRegistro.setLayout(PantallaRegistroLayout);
        PantallaRegistroLayout.setHorizontalGroup(
            PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaRegistroLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnviarInicioSesion)
                    .addGroup(PantallaRegistroLayout.createSequentialGroup()
                        .addGroup(PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(textPassword))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        PantallaRegistroLayout.setVerticalGroup(
            PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaRegistroLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(PantallaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnEnviarInicioSesion)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(PantallaRegistro, "card4");
        PantallaRegistro.getAccessibleContext().setAccessibleName("Pantalla_registro");

        btnVerRuta2.setText("Ver Rutas");
        btnVerRuta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRuta2ActionPerformed(evt);
            }
        });

        btnCrearRuta.setText("Crear Rutas");
        btnCrearRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRutaActionPerformed(evt);
            }
        });

        btnDescargarFicha.setText("Descargar Ficha");
        btnDescargarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarFichaActionPerformed(evt);
            }
        });

        btnCrearCalendar.setText("Crear calendario");
        btnCrearCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCalendarActionPerformed(evt);
            }
        });

        btnModificarRuta.setText("Modificar Ruta");
        btnModificarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRutaActionPerformed(evt);
            }
        });

        btnBorrarRuta.setText("Borrar ruta");
        btnBorrarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRutaActionPerformed(evt);
            }
        });

        btnValidarRuta.setText("Validar ruta");
        btnValidarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarRutaActionPerformed(evt);
            }
        });

        btnValidarUsuario.setText("Validar usuario");
        btnValidarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaMenuLayout = new javax.swing.GroupLayout(PantallaMenu);
        PantallaMenu.setLayout(PantallaMenuLayout);
        PantallaMenuLayout.setHorizontalGroup(
            PantallaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaMenuLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addGroup(PantallaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValidarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerRuta2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescargarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        PantallaMenuLayout.setVerticalGroup(
            PantallaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaMenuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnVerRuta2)
                .addGap(18, 18, 18)
                .addComponent(btnCrearRuta)
                .addGap(18, 18, 18)
                .addComponent(btnDescargarFicha)
                .addGap(18, 18, 18)
                .addComponent(btnCrearCalendar)
                .addGap(18, 18, 18)
                .addComponent(btnModificarRuta)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarRuta)
                .addGap(18, 18, 18)
                .addComponent(btnValidarRuta)
                .addGap(20, 20, 20)
                .addComponent(btnValidarUsuario)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(PantallaMenu, "card5");

        TablaRutasNoValidadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Rutas no validadas"));
        jScrollPane2.setViewportView(TablaRutasNoValidadas);

        btnValidaRUTA.setText("Validar");
        btnValidaRUTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidaRUTAActionPerformed(evt);
            }
        });

        btnVolverValidaRutas.setText("Volver");
        btnVolverValidaRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverValidaRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaValidarRutasLayout = new javax.swing.GroupLayout(PantallaValidarRutas);
        PantallaValidarRutas.setLayout(PantallaValidarRutasLayout);
        PantallaValidarRutasLayout.setHorizontalGroup(
            PantallaValidarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaValidarRutasLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(PantallaValidarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PantallaValidarRutasLayout.createSequentialGroup()
                        .addComponent(btnVolverValidaRutas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidaRUTA))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PantallaValidarRutasLayout.setVerticalGroup(
            PantallaValidarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaValidarRutasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PantallaValidarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidaRUTA)
                    .addComponent(btnVolverValidaRutas))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(PantallaValidarRutas, "card6");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios no validados"));
        jScrollPane3.setViewportView(TablaUsuarios);

        btnValidarUsuarios.setText("Validar");
        btnValidarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarUsuariosActionPerformed(evt);
            }
        });

        btnVolverValidaUsuario.setText("Volver");
        btnVolverValidaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverValidaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaValidarUsuariosLayout = new javax.swing.GroupLayout(PantallaValidarUsuarios);
        PantallaValidarUsuarios.setLayout(PantallaValidarUsuariosLayout);
        PantallaValidarUsuariosLayout.setHorizontalGroup(
            PantallaValidarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaValidarUsuariosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PantallaValidarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PantallaValidarUsuariosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVolverValidaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidarUsuarios))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PantallaValidarUsuariosLayout.setVerticalGroup(
            PantallaValidarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaValidarUsuariosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PantallaValidarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidarUsuarios)
                    .addComponent(btnVolverValidaUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PantallaValidarUsuarios, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        PantallaPrinci.setVisible(false);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(true);
        PantallaVerRutas.setVisible(false);
        PantallaValidarRutas.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnEnviarInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarInicioSesionActionPerformed
        String nombre = textUsuario.getText();
        char[] pass = textPassword.getPassword();
        String password = "";
        for (char c : pass) {
            password += c;
        }
        user = usuarios.buscarUsuPorNomPassword(nombre, password);
        if (user == null) {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña no validos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (user instanceof Administrador) {
                PantallaPrinci.setVisible(false);
                PantallaMenu.setVisible(true);
                PantallaRegistro.setVisible(false);
                PantallaVerRutas.setVisible(false);
            } else if (user instanceof Profesor) {
                PantallaPrinci.setVisible(false);
                PantallaMenu.setVisible(true);
                btnValidarUsuario.setVisible(false);
                btnValidarRuta.setVisible(false);
                btnBorrarRuta.setVisible(false);
                btnModificarRuta.setVisible(false);
                PantallaRegistro.setVisible(false);
                PantallaVerRutas.setVisible(false);
            } else if (user instanceof Disenador_rutas) {
                PantallaPrinci.setVisible(false);
                PantallaMenu.setVisible(true);
                btnValidarUsuario.setVisible(false);
                btnValidarRuta.setVisible(false);
                btnBorrarRuta.setVisible(false);
                btnModificarRuta.setVisible(false);
                btnCrearCalendar.setVisible(false);
                PantallaRegistro.setVisible(false);
                PantallaVerRutas.setVisible(false);
            } else if (user instanceof Alumno) {
                PantallaPrinci.setVisible(false);
                PantallaMenu.setVisible(true);
                btnValidarUsuario.setVisible(false);
                btnValidarRuta.setVisible(false);
                btnBorrarRuta.setVisible(false);
                btnModificarRuta.setVisible(false);
                btnCrearCalendar.setVisible(false);
                btnDescargarFicha.setVisible(false);
                PantallaRegistro.setVisible(false);
                PantallaVerRutas.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnEnviarInicioSesionActionPerformed

    private void btnVerRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRutasActionPerformed
        cargarTablaRutas();
        PantallaPrinci.setVisible(false);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(false);
        PantallaVerRutas.setVisible(true);
        btnValoracion.setVisible(false);
        PantallaValidarRutas.setVisible(false);
        btnVolverVerRutas.setVisible(false);
    }//GEN-LAST:event_btnVerRutasActionPerformed

    private void btnVerRuta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRuta2ActionPerformed
        cargarTablaRutas();
        PantallaPrinci.setVisible(false);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(false);
        PantallaVerRutas.setVisible(true);
        PantallaValidarRutas.setVisible(false);
    }//GEN-LAST:event_btnVerRuta2ActionPerformed

    private void btnCrearRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearRutaActionPerformed

    private void btnDescargarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescargarFichaActionPerformed

    private void btnCrearCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCalendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCalendarActionPerformed

    private void btnModificarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarRutaActionPerformed

    private void btnBorrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarRutaActionPerformed

    private void btnValidarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarRutaActionPerformed
        cargarTablaRutasNoValidadas();
        PantallaValidarRutas.setVisible(true);
        PantallaPrinci.setVisible(false);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(false);
        PantallaVerRutas.setVisible(false);

    }//GEN-LAST:event_btnValidarRutaActionPerformed

    private void btnValidarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarUsuarioActionPerformed
        cargarTablaUsuariosNoValidados();
        PantallaValidarRutas.setVisible(false);
        PantallaPrinci.setVisible(false);
        PantallaMenu.setVisible(false);
        PantallaRegistro.setVisible(false);
        PantallaVerRutas.setVisible(false);
        PantallaValidarUsuarios.setVisible(true);
    }//GEN-LAST:event_btnValidarUsuarioActionPerformed

    private void btnValidaRUTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidaRUTAActionPerformed
        int seleccion = TablaRutasNoValidadas.getSelectedRow();
        if (seleccion != -1) {
            String id_string = (String) TablaRutasNoValidadas.getValueAt(seleccion, 0);
            int id = Integer.parseInt(id_string);
            Ruta ruta = rutas.obtenerRutaPorId(id);
            if (!rutas.validarRuta(ruta)) {
                JOptionPane.showMessageDialog(null, "No se pudo validar la ruta", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                cargarTablaRutasNoValidadas();
                JOptionPane.showMessageDialog(null, "Ruta Validada", "", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una ruta", "", JOptionPane.NO_OPTION);
        }

    }//GEN-LAST:event_btnValidaRUTAActionPerformed

    private void btnValidarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarUsuariosActionPerformed
        int seleccion = TablaUsuarios.getSelectedRow();
        if (seleccion != -1) {
            String id_string = (String) TablaUsuarios.getValueAt(seleccion, 0);
            int id = Integer.parseInt(id_string);
            Usuario usu=usuarios.obtenerUsuarioPorId(id);
            if (!usuarios.validarUsuario(usu)) {
                JOptionPane.showMessageDialog(null, "No se pudo validar al usuario", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                cargarTablaUsuariosNoValidados();
                JOptionPane.showMessageDialog(null, "Usuario Validado", "", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un usuario", "", JOptionPane.NO_OPTION);
        }
    }//GEN-LAST:event_btnValidarUsuariosActionPerformed

    private void btnVolverVerRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverVerRutasActionPerformed
        if (user instanceof Administrador) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Profesor) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Disenador_rutas) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Alumno) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            btnDescargarFicha.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        }
    }//GEN-LAST:event_btnVolverVerRutasActionPerformed

    private void btnVolverValidaRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverValidaRutasActionPerformed
    if (user instanceof Administrador) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Profesor) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Disenador_rutas) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Alumno) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            btnDescargarFicha.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        }
    }//GEN-LAST:event_btnVolverValidaRutasActionPerformed

    private void btnVolverValidaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverValidaUsuarioActionPerformed
    if (user instanceof Administrador) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Profesor) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Disenador_rutas) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        } else if (user instanceof Alumno) {
            PantallaPrinci.setVisible(false);
            PantallaMenu.setVisible(true);
            btnValidarUsuario.setVisible(false);
            btnValidarRuta.setVisible(false);
            btnBorrarRuta.setVisible(false);
            btnModificarRuta.setVisible(false);
            btnCrearCalendar.setVisible(false);
            btnDescargarFicha.setVisible(false);
            PantallaRegistro.setVisible(false);
            PantallaVerRutas.setVisible(false);
        }
    }//GEN-LAST:event_btnVolverValidaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    public void cargarTablaRutas() {
        LinkedList<Ruta> listarutas = rutas.muestraRutas();
        TablaRutasNoValidadas.removeAll();
        String[] columnas = {"ID", "Nombre", "Distancia", "Duracion", "Clasificacion", "Nivel de riesgo", "Nivel de esfuerzo", "Desnivel acumulado", "Tipo de terreno", "Valoracion media"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        TablaRutas.setModel(modelo);
        for (Ruta r : listarutas) {
            String[] datos = {String.valueOf(r.getId_ruta()), r.getNombre(), String.valueOf(r.getDistancia_total()), String.valueOf(r.getDuracion()), r.getClasificacion().toString(),
                String.valueOf(r.getNivel_riesgo()), String.valueOf(r.getNivel_esfuerzo()), String.valueOf(r.getDesnivel_acumulado()),
                String.valueOf(r.getTipo_terreno()), String.valueOf(r.getValoracion_media())};
            modelo.addRow(datos);
        }

    }

    public void cargarTablaRutasNoValidadas() {
        ArrayList<Ruta> noValidadas = rutas.rutasNoValidadas();
        TablaRutasNoValidadas.removeAll();
        String[] columnas = {"ID", "Nombre", "Distancia", "Duracion", "Clasificacion", "Nivel de riesgo", "Nivel de esfuerzo", "Desnivel acumulado", "Tipo de terreno", "Valoracion media"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        TablaRutasNoValidadas.setModel(modelo);
        for (Ruta r : noValidadas) {
            String[] datos = {String.valueOf(r.getId_ruta()), r.getNombre(), String.valueOf(r.getDistancia_total()), String.valueOf(r.getDuracion()), r.getClasificacion().toString(),
                String.valueOf(r.getNivel_riesgo()), String.valueOf(r.getNivel_esfuerzo()), String.valueOf(r.getDesnivel_acumulado()),
                String.valueOf(r.getTipo_terreno()), String.valueOf(r.getValoracion_media())};
            modelo.addRow(datos);
        }
    }

    public void cargarTablaUsuariosNoValidados() {
        ArrayList<Usuario> noValidados = usuarios.listarUsuariosNoValidados();
        TablaUsuarios.removeAll();
        String[] columnas = {"ID", "Nombre", "Apellidos", "Fecha de nacimiento", "Rol del usuario"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        TablaUsuarios.setModel(modelo);
        for (Usuario usu : noValidados) {
            String[] datos = {String.valueOf(usu.getId()), usu.getNombre(), usu.getApellidos(), usu.getFecha_nac().toString(), usu.getRol().toString()};
            modelo.addRow(datos);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PantallaMenu;
    private javax.swing.JPanel PantallaPrinci;
    private javax.swing.JPanel PantallaRegistro;
    private javax.swing.JPanel PantallaValidarRutas;
    private javax.swing.JPanel PantallaValidarUsuarios;
    private javax.swing.JPanel PantallaVerRutas;
    private javax.swing.JTable TablaRutas;
    private javax.swing.JTable TablaRutasNoValidadas;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnBorrarRuta;
    private javax.swing.JButton btnCrearCalendar;
    private javax.swing.JButton btnCrearRuta;
    private javax.swing.JButton btnDescargarFicha;
    private javax.swing.JButton btnEnviarInicioSesion;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnModificarRuta;
    private javax.swing.JButton btnResena;
    private javax.swing.JButton btnValidaRUTA;
    private javax.swing.JButton btnValidarRuta;
    private javax.swing.JButton btnValidarUsuario;
    private javax.swing.JButton btnValidarUsuarios;
    private javax.swing.JButton btnValoracion;
    private javax.swing.JButton btnVerRuta2;
    private javax.swing.JButton btnVerRutas;
    private javax.swing.JButton btnVolverValidaRutas;
    private javax.swing.JButton btnVolverValidaUsuario;
    private javax.swing.JButton btnVolverVerRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
